{
  ["193e8362-f06c-42a9-b01e-c3bdaea65365"] = {
    ["name"] = "auto_moto",
    ["listings"] = {
      ["PinkSlip.AMC_quad"] = {
        ["item"] = "PinkSlip.AMC_quad",
        ["price"] = 150000,
        ["buybackRate"] = 100,
        ["stock"] = 999999999999,
        ["available"] = 999999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.AMC_bmw_classic"] = {
        ["item"] = "PinkSlip.AMC_bmw_classic",
        ["price"] = 15000,
        ["buybackRate"] = 100,
        ["stock"] = 999999999999,
        ["available"] = 999999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.AMC_bmw_custom"] = {
        ["item"] = "PinkSlip.AMC_bmw_custom",
        ["price"] = 2000,
        ["buybackRate"] = 100,
        ["stock"] = 999999999999,
        ["available"] = 999999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.80kz1000"] = {
        ["item"] = "PinkSlip.80kz1000",
        ["price"] = 10000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.vino125"] = {
        ["item"] = "PinkSlip.vino125",
        ["price"] = 500,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.vino125b"] = {
        ["item"] = "PinkSlip.vino125b",
        ["price"] = 3000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
    },
    ["ID"] = "193e8362-f06c-42a9-b01e-c3bdaea65365",
    ["isBeingManaged"] = true,
    ["restockHrs"] = 0,
    ["nextRestock"] = 0,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["e2b04531-6b80-4ea8-a082-3b9d156d582f"] = {
    ["name"] = "stalker_store",
    ["listings"] = {
    },
    ["ID"] = "e2b04531-6b80-4ea8-a082-3b9d156d582f",
    ["isBeingManaged"] = false,
    ["restockHrs"] = 48,
    ["nextRestock"] = 23,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["f83ccb57-cf59-4235-98e4-5db0ea173319"] = {
    ["name"] = "auto_crossover",
    ["listings"] = {
      ["PinkSlip.OffRoad"] = {
        ["item"] = "PinkSlip.OffRoad",
        ["price"] = 20000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.90niva"] = {
        ["item"] = "PinkSlip.90niva",
        ["price"] = 20000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.PickUpTruck"] = {
        ["item"] = "PinkSlip.PickUpTruck",
        ["price"] = 90000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.PickUpTruckLightsFire"] = {
        ["item"] = "PinkSlip.PickUpTruckLightsFire",
        ["price"] = 96000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.PickUpTruckLights"] = {
        ["item"] = "PinkSlip.PickUpTruckLights",
        ["price"] = 96000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.PickUpVanLights"] = {
        ["item"] = "PinkSlip.PickUpVanLights",
        ["price"] = 120000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.PickUpVanLightsPolice"] = {
        ["item"] = "PinkSlip.PickUpVanLightsPolice",
        ["price"] = 120000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.PickUpVanLightsFire"] = {
        ["item"] = "PinkSlip.PickUpVanLightsFire",
        ["price"] = 120000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.PickUpVan"] = {
        ["item"] = "PinkSlip.PickUpVan",
        ["price"] = 115000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
    },
    ["ID"] = "f83ccb57-cf59-4235-98e4-5db0ea173319",
    ["isBeingManaged"] = false,
    ["restockHrs"] = 0,
    ["nextRestock"] = 0,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["22c1d491-713a-40ae-9063-2ebea37e4bb2"] = {
    ["name"] = "auto_truck",
    ["listings"] = {
      ["PinkSlip.VanSpecial"] = {
        ["item"] = "PinkSlip.VanSpecial",
        ["price"] = 110000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.Van_MassGenFac"] = {
        ["item"] = "PinkSlip.Van_MassGenFac",
        ["price"] = 115000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.Van_KnoxDisti"] = {
        ["item"] = "PinkSlip.Van_KnoxDisti",
        ["price"] = 115000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.Van_LectroMax"] = {
        ["item"] = "PinkSlip.Van_LectroMax",
        ["price"] = 115000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.VanRadio_3N"] = {
        ["item"] = "PinkSlip.VanRadio_3N",
        ["price"] = 115000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.Van_Transit"] = {
        ["item"] = "PinkSlip.Van_Transit",
        ["price"] = 115000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.VanRadio"] = {
        ["item"] = "PinkSlip.VanRadio",
        ["price"] = 115000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.StepVan"] = {
        ["item"] = "PinkSlip.StepVan",
        ["price"] = 180000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.StepVan_Heralds"] = {
        ["item"] = "PinkSlip.StepVan_Heralds",
        ["price"] = 180000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.StepVanMail"] = {
        ["item"] = "PinkSlip.StepVanMail",
        ["price"] = 180000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.StepVan_Scarlet"] = {
        ["item"] = "PinkSlip.StepVan_Scarlet",
        ["price"] = 180000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
    },
    ["ID"] = "22c1d491-713a-40ae-9063-2ebea37e4bb2",
    ["isBeingManaged"] = false,
    ["restockHrs"] = 48,
    ["nextRestock"] = 21,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["2f108035-bb7a-464d-9d2e-90905aad20f8"] = {
    ["name"] = "auto_passenger",
    ["listings"] = {
      ["PinkSlip.SmallCar"] = {
        ["item"] = "PinkSlip.SmallCar",
        ["price"] = 20000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.ModernCar02"] = {
        ["item"] = "PinkSlip.ModernCar02",
        ["price"] = 24000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.ModernCar"] = {
        ["item"] = "PinkSlip.ModernCar",
        ["price"] = 24000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.CarTaxi"] = {
        ["item"] = "PinkSlip.CarTaxi",
        ["price"] = 35000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.CarLights"] = {
        ["item"] = "PinkSlip.CarLights",
        ["price"] = 35000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.CarStationWagon"] = {
        ["item"] = "PinkSlip.CarStationWagon",
        ["price"] = 40000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.SportsCar"] = {
        ["item"] = "PinkSlip.SportsCar",
        ["price"] = 60000,
        ["buybackRate"] = 100,
        ["stock"] = 99999999,
        ["available"] = 99999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
    },
    ["ID"] = "2f108035-bb7a-464d-9d2e-90905aad20f8",
    ["isBeingManaged"] = false,
    ["restockHrs"] = 48,
    ["nextRestock"] = 26,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["36f46d36-7d69-4e4b-aad6-e3ffba576f63"] = {
    ["name"] = "auto_army",
    ["listings"] = {
      ["PinkSlip.92amgeneralM998"] = {
        ["item"] = "PinkSlip.92amgeneralM998",
        ["price"] = 300000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.83amgeneralM923"] = {
        ["item"] = "PinkSlip.83amgeneralM923",
        ["price"] = 500000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["PinkSlip.78amgeneralM35A2"] = {
        ["item"] = "PinkSlip.78amgeneralM35A2",
        ["price"] = 640000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999999,
        ["available"] = 9999999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
    },
    ["ID"] = "36f46d36-7d69-4e4b-aad6-e3ffba576f63",
    ["isBeingManaged"] = true,
    ["restockHrs"] = 48,
    ["nextRestock"] = 27,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["dcee6118-8819-4fc5-8f29-179162810486"] = {
    ["name"] = "auto_trailer",
    ["listings"] = {
      ["PinkSlip.Trailer"] = {
        ["item"] = "PinkSlip.Trailer",
        ["price"] = 120000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999,
        ["available"] = 9999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
      ["PinkSlip.TrailerM101A3cargo"] = {
        ["item"] = "PinkSlip.TrailerM101A3cargo",
        ["price"] = 200000,
        ["buybackRate"] = 100,
        ["stock"] = 9999999,
        ["available"] = 9999999,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = false,
      },
    },
    ["ID"] = "dcee6118-8819-4fc5-8f29-179162810486",
    ["isBeingManaged"] = false,
    ["restockHrs"] = 0,
    ["nextRestock"] = 0,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["9831d1a3-983b-47cb-bf26-ec6a84700110"] = {
    ["name"] = "auto_parts",
    ["listings"] = {
    },
    ["ID"] = "9831d1a3-983b-47cb-bf26-ec6a84700110",
    ["isBeingManaged"] = true,
    ["restockHrs"] = 48,
    ["nextRestock"] = 29,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["ef6ed358-cf07-4556-b128-e1bc2a5c4662"] = {
    ["name"] = "alexandria_construction",
    ["listings"] = {
      ["Base.NailsBox"] = {
        ["item"] = "Base.NailsBox",
        ["price"] = 50,
        ["buybackRate"] = 50,
        ["stock"] = 99,
        ["available"] = 99,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["Base.PropaneTank"] = {
        ["item"] = "Base.PropaneTank",
        ["price"] = 500,
        ["buybackRate"] = 50,
        ["stock"] = 99,
        ["available"] = 99,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
    },
    ["ID"] = "ef6ed358-cf07-4556-b128-e1bc2a5c4662",
    ["isBeingManaged"] = true,
    ["restockHrs"] = 48,
    ["nextRestock"] = 34,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["e5f0d1f1-95ef-4651-8971-2efd15d84341"] = {
    ["name"] = "alexandria_farmer",
    ["listings"] = {
      ["farming.Cabbage"] = {
        ["item"] = "farming.Cabbage",
        ["price"] = 100,
        ["buybackRate"] = 50,
        ["stock"] = 0,
        ["available"] = 1,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["farming.Potato"] = {
        ["item"] = "farming.Potato",
        ["price"] = 50,
        ["buybackRate"] = 50,
        ["stock"] = 0,
        ["available"] = 0,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
    },
    ["ID"] = "e5f0d1f1-95ef-4651-8971-2efd15d84341",
    ["isBeingManaged"] = false,
    ["restockHrs"] = 0,
    ["nextRestock"] = 0,
    ["managerIDs"] = {
    },
    ["cash"] = -50,
  },
  ["5061b85f-1818-4550-9906-6e608b4df8c6"] = {
    ["name"] = "alexandria_fishing",
    ["listings"] = {
      ["Base.Trout"] = {
        ["item"] = "Base.Trout",
        ["price"] = 200,
        ["buybackRate"] = 50,
        ["stock"] = 5,
        ["available"] = 5,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
    },
    ["ID"] = "5061b85f-1818-4550-9906-6e608b4df8c6",
    ["isBeingManaged"] = true,
    ["restockHrs"] = 48,
    ["nextRestock"] = 39,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["2cf39c32-b108-4df8-867f-07467d666731"] = {
    ["name"] = "alexandria_hunting",
    ["listings"] = {
      ["Base.Rabbitmeat"] = {
        ["item"] = "Base.Rabbitmeat",
        ["price"] = 150,
        ["buybackRate"] = 90,
        ["stock"] = 0,
        ["available"] = 0,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["Base.Smallbirdmeat"] = {
        ["item"] = "Base.Smallbirdmeat",
        ["price"] = 250,
        ["buybackRate"] = 90,
        ["stock"] = 0,
        ["available"] = 0,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["Base.FrogMeat"] = {
        ["item"] = "Base.FrogMeat",
        ["price"] = 150,
        ["buybackRate"] = 90,
        ["stock"] = 0,
        ["available"] = 0,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
      ["Base.Smallanimalmeat"] = {
        ["item"] = "Base.Smallanimalmeat",
        ["price"] = 100,
        ["buybackRate"] = 90,
        ["stock"] = 0,
        ["available"] = 0,
        ["storeID"] = false,
        ["reselling"] = true,
        ["alwaysShow"] = true,
      },
    },
    ["ID"] = "2cf39c32-b108-4df8-867f-07467d666731",
    ["isBeingManaged"] = false,
    ["restockHrs"] = 0,
    ["nextRestock"] = 0,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
  ["4c7243f1-b057-43f6-9493-2cc3aeec6c66"] = {
    ["name"] = "market_pawnshop",
    ["listings"] = {
      ["Base.Necklace_DogTag"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_DogTag",
        ["price"] = 25,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_Gold",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_GoldRuby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_GoldRuby",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_GoldDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_GoldDiamond",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_SilverSapphire"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_SilverSapphire",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_SilverCrucifix"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_SilverCrucifix",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_SilverDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_SilverDiamond",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_Crucifix"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_Crucifix",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_YingYang"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_YingYang",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Necklace_Pearl"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Necklace_Pearl",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NecklaceLong_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NecklaceLong_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NecklaceLong_GoldDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NecklaceLong_GoldDiamond",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NecklaceLong_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NecklaceLong_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NecklaceLong_SilverEmerald"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NecklaceLong_SilverEmerald",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NecklaceLong_SilverSapphire"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NecklaceLong_SilverSapphire",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NecklaceLong_SilverDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NecklaceLong_SilverDiamond",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NecklaceLong_Amber"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NecklaceLong_Amber",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NoseRing_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NoseRing_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NoseRing_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NoseRing_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NoseStud_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NoseStud_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.NoseStud_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.NoseStud_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_LoopLrg_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_LoopLrg_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_LoopLrg_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_LoopLrg_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_LoopMed_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_LoopMed_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_LoopMed_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_LoopMed_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_LoopSmall_Silver_Both"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_LoopSmall_Silver_Both",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_LoopSmall_Silver_Top"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_LoopSmall_Silver_Top",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_LoopSmall_Gold_Both"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_LoopSmall_Gold_Both",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_LoopSmall_Gold_Top"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_LoopSmall_Gold_Top",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Stud_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Stud_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Stud_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Stud_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Stone_Sapphire"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Stone_Sapphire",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Stone_Emerald"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Stone_Emerald",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Stone_Ruby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Stone_Ruby",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Pearl"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Pearl",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Dangly_Sapphire"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Dangly_Sapphire",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Dangly_Emerald"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Dangly_Emerald",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Dangly_Ruby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Dangly_Ruby",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Dangly_Diamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Dangly_Diamond",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Earring_Dangly_Pearl"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Earring_Dangly_Pearl",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_MiddleFinger_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_MiddleFinger_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_MiddleFinger_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_MiddleFinger_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_RingFinger_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_RingFinger_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_RingFinger_Gold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_RingFinger_Gold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_MiddleFinger_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_MiddleFinger_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_MiddleFinger_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_MiddleFinger_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_RingFinger_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_RingFinger_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_RingFinger_Silver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_RingFinger_Silver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_MiddleFinger_SilverDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_MiddleFinger_SilverDiamond",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_MiddleFinger_SilverDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_MiddleFinger_SilverDiamond",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_RingFinger_SilverDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_RingFinger_SilverDiamond",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_RingFinger_SilverDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_RingFinger_SilverDiamond",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_MiddleFinger_GoldRuby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_MiddleFinger_GoldRuby",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_MiddleFinger_GoldRuby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_MiddleFinger_GoldRuby",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_RingFinger_GoldRuby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_RingFinger_GoldRuby",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_RingFinger_GoldRuby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_RingFinger_GoldRuby",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_MiddleFinger_GoldDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_MiddleFinger_GoldDiamond",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_MiddleFinger_GoldDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_MiddleFinger_GoldDiamond",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Right_RingFinger_GoldDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Right_RingFinger_GoldDiamond",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring_Left_RingFinger_GoldDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring_Left_RingFinger_GoldDiamond",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.WristWatch_Right_ClassicBlack"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.WristWatch_Right_ClassicBlack",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.WristWatch_Left_ClassicBlack"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.WristWatch_Left_ClassicBlack",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.WristWatch_Right_ClassicBrown"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.WristWatch_Right_ClassicBrown",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.WristWatch_Left_ClassicBrown"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.WristWatch_Left_ClassicBrown",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.WristWatch_Right_ClassicMilitary"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.WristWatch_Right_ClassicMilitary",
        ["price"] = 300,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.WristWatch_Left_ClassicMilitary"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.WristWatch_Left_ClassicMilitary",
        ["price"] = 300,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.WristWatch_Right_ClassicGold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.WristWatch_Right_ClassicGold",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.WristWatch_Left_ClassicGold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.WristWatch_Left_ClassicGold",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_BangleRightGold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_BangleRightGold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_BangleLeftGold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_BangleLeftGold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_ChainRightGold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_ChainRightGold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_ChainLeftGold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_ChainLeftGold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_BangleRightSilver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_BangleRightSilver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_BangleLeftSilver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_BangleLeftSilver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_ChainRightSilver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_ChainRightSilver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_ChainLeftSilver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_ChainLeftSilver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_RightFriendshipTINT"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_RightFriendshipTINT",
        ["price"] = 25,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Bracelet_LeftFriendshipTINT"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Bracelet_LeftFriendshipTINT",
        ["price"] = 25,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_DangleGold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_DangleGold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_DangleGoldRuby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_DangleGoldRuby",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_DangleSilver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_DangleSilver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_DangleSilverDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_DangleSilverDiamond",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_RingGold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_RingGold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_RingGoldDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_RingGoldDiamond",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_RingGoldRuby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_RingGoldRuby",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_RingSilver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_RingSilver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_RingSilverAmethyst"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_RingSilverAmethyst",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_RingSilverDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_RingSilverDiamond",
        ["price"] = 150,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_RingSilverRuby"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_RingSilverRuby",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_StudGold"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_StudGold",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_StudGoldDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_StudGoldDiamond",
        ["price"] = 200,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_StudSilver"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_StudSilver",
        ["price"] = 50,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.BellyButton_StudSilverDiamond"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.BellyButton_StudSilverDiamond",
        ["price"] = 100,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
      ["Base.Ring"] = {
        ["alwaysShow"] = false,
        ["available"] = 0,
        ["buybackRate"] = 100,
        ["item"] = "Base.Ring",
        ["price"] = 25,
        ["reselling"] = true,
        ["stock"] = 0,
        ["storeID"] = false,
      },
    },
    ["ID"] = "4c7243f1-b057-43f6-9493-2cc3aeec6c66",
    ["isBeingManaged"] = false,
    ["restockHrs"] = 0,
    ["nextRestock"] = 0,
    ["managerIDs"] = {
    },
    ["cash"] = 0,
  },
}